# Generated by Django 4.0.5 on 2022-08-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_tiempo'),
        ('cursos', '0005_alter_cursos_curso_alter_cursos_i_and_more'),
    ]

    operations = [
    ]
